config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals, only: [:new, :create, :destroy, :edit, :update]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :user_id, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true }
  has_many :goals
  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(32)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(32)
    self.save
    self.session_token
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    return nil unless logged_in?
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_current_user!
    redirect_to new_session_url unless logged_in?
  end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController


  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    @goal.completed = false
    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def new
    @goal = Goal.new
  end

  def edit
    find_goal
  end

  def update
    find_goal
    return unless owns_goal?
    if @goal.update_attributes(goal_params)
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_goal
    return unless owns_goal?
    @goal.destroy
    redirect_to user_url(current_user)
  end


  private

  def find_goal
    @goal ||= Goal.find(params[:id].to_i)
  end

  def owns_goal?
    unless find_goal.user_id == current_user.id
      render text: "get out", status: :forbidden
      return false
    end
    true
  end


  def goal_params
    params.require(:goal).permit(:body, :private, :completed)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:errors] = ["Bad login info"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @goals = Goal.where(user_id: params[:id], private: false)
    @goals += Goal.where(user_id: params[:id], private: true) if current_user.id == params[:id].to_i
    @user = User.find((params[:id]))
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action= "<%= goal_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <label>
    Goal <textarea name="goal[body]" rows="8" cols="40"> <%= @goal.body %> </textarea>
  </label>
  <input type="hidden" name="goal[completed]" value="false">
  <label><input name="goal[completed]" type="checkbox"
    <%= @goal.completed ? "checked" : "" %>
    > Completed </label><br>

<input type="submit" value="Edit Goal">
</form>

app/views/goals/new.html.erb
<h1>Create Goal</h1>

<form action= "<%= goals_url %>" method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <label>
    Goal <textarea name="goal[body]" rows="8" cols="40"> <%= @goal.body %> </textarea>
  </label>
  <label>
    Private<input type="radio" name="goal[private]" value="true">
  </label>
  <label>
    Public<input type="radio" name="goal[private]" value="false">
  </label>


<input type="submit" value="Create Goal">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%=error%></li>
  <%end%>
<%end%>

<% if logged_in? %>
<%= current_user.username %>
<%= button_to "Log Out", session_url, method: :delete%>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action= "<%=users_url%>" method="post">
  <label>Username
    <input type="text" name="user[username]" value="<%=@user.username%>">
  </label>
  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Submit">

</form>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>
<% @goals.each do |g| %>
  <li><%= g.body %>
  <%=link_to "Edit Goal", edit_goal_url(g) if current_user.id == g.user_id%>
  <%=link_to "Delete Goal", goal_url(g), method: :delete if current_user.id == g.user_id%>
  <%= "✔" if g.completed %>
</li>
<% end %>


<%=link_to "Add Goal", new_goal_url %>